query Guides {
  guides {
    data {
      id
      attributes {
        title
        coverImage {
          data {
            attributes {
              url
            }
          }
        }
        shortDescription
      }
    }
  }
}
